var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                         o                                                                        ",
   "                              w       xxxxxxxx                                                                    ",
   "                             xxx                                                                                  ",
   "                          x!!!!!!!!!x          xxxxxxxx                                                           ",
   "                          x!!!!!!!!!x                                                                             ",
   "                          x!!!!!!!!!x                                                                             ",
   "                          xxvxxxxxxvx   xxxxxxx                                                                   ",
   "                       o                                                                                          ",
   "                     xxx                        o                                                                 ",
   "               p xxxxx                        xxxxx                                                               ",
   "              xxxx                                   xxxx                                                         ",
   "     @     xxxx                                  x      x                                                         ",
   "    xxx                                          xxx    x                     o                                   ",
   "                              xxxx   xxxxx!!!!!!!x      x             x!!!!xxxxxx                                x",
   "!!!!!!!!!!!!!!!!!!!!!!!xxx    x          xxxxxxxxx    xxx         xxxxx!!!!x    =                                x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!x          o                   x          s  x!!!!x    x           xxxxxxx        oo    x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!x        xxxxxx                x             x!!!!x    xxxxxxxxxxxxx     xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxx                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                            x!!!!!!x                                          ",
   "                                                            x!!!!!!x                                          ",
   "                                                            x!!!!!!x                                          ",
   "                                                            xxxxvxxx                                          ",
   "                                                                                                              ",
   "                    x!!!!!!!!!!!x                                                                             ",
   "                    x!!!!!!!!!!!x                                                                             ",
   "                    x!!!!!!!!!!!x                                                                             ",
   "                    x!!!!!!!!!!!x                                                                             ",
   "                    xvxxxxvxxxxvx                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                           x  ",
   "  x                                                 w           x            o                             x  ",
   "  x                      o                      xxxxxxxxxxxxx!!!!!!!!xxxxxxxxx                             x  ",
   "  x                    xxxxxx                xxxx           x!!!!!!!!x                                     x  ",
   "  x                                                         x!!!!!!!!x        xxxxxx          o            x  ",
   "  x              op                      xxx                xxxxxxxxxx                    xxxxxxxxx        x  ",
   "  x        o   xxxxxx!!!!!!!!!!xx                 o                           x!!!!!!!!!!!!!!!!!!!x        x  ",
   "  x       xxx       x!!!!!!!!!!!x    o           xx                           xxxxxxxxxxxxxxxxxxxxx        x  ",
   "  x        xx       x!!!!!!!!!!!x     xxx       xxxx!!!xxxx               s                                x  ",
   "  x      @          x!!!!!!!!!!!x             xxxxxxxxx        oo                                     o    x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                x!!!!!!!!!x                                                                   ",
   "                                xxxxxxxxxxx                                                                   "],
   ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                             x!!!!!x          ",
   "                                                                                             x!!!!!x          ",
   "                                                                                             x!!!!!x          ",
   "                                                                                             x!!!!!x          ",
   "                                                                                             xxxvxxx          ",
   "    @                                                                                                         ",
   "  xxxxxx     x                                                                                                ",
   "       x     x                                                                                                ",
   "       x  o  x                                                                           o       xxxxx    x   ",
   "       x     x                                                                          xxxx       x      x   ",
   "       x  p  x                                                         s             xxxxxxxxxx    x      x   ",
   "       x     x                                                o                 w         x        x o    x   ",
   "       x     x                                                x               xxxx        x o     xxxx!!!!x   ",
   "                                                             xxxx             x           xxxxxxxxxxxxxxxxx   ",
   "                                                           xxxxxxx            x                               ",
   "                                                              x!!!!!!!!!!!!!!!x                               ",
   "                                                              x!!!!!!!!!!!!!!!x                               ",
   "                                                     p        x!!!!!!!!!!!!!!!x                               ",
   "                                                  xxxxxxxxxxxxxxxvxxxxxxxxvxxx                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                            xxxxxx                   o                                        ",
   "                           o                                                                                  ",
   "  x                    xxxxxxxxxxxxxxxx                o            xxxxxx                                    ",
   "  x              xxxxxxx!!!!!!!!!!!!!!=              xxxxxx                                                   ",
   "  x          x x xxxxxxxxxx!!!!!!!!!!!x         s                                                             ",
   "  x              xxxxxxxxxxxxx!!!!!!!!=                                                                       ",
   "  xxxxxxx        xxxxxxxxxxxxxxx!!!!!!x      xxxxxx             xxxxx                                         ",
   "        x        xxxxxxxxxxxxxxxxx!!!!x   o                                                      x         o  ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxx",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                     ",
   "                                                                     ",
   "                                                                     ",
   "                                                                     ",
   "                                                                     ",
   "  x                                                               x  ",
   "  x                                                               x  ",
   "  x                                                               x  ",
   "  x                                                               x  ",
   "  x       =v         =v  =v=   =v     v=                          x  ",
   "  x       =v         =v  v=v   v=v    =v                          x  ",
   "  x       =v   =v=   =v  =v=   =v=v=  v=                          x  ",
   "  x        =v =v=v= =v   v=v   v= =v= =v                          x  ",
   "  x         =v=v =v=v    =v=   =v  =v=v=                          x  ",
   "  x          =v   =v     v=v   v=   =v=v                          x  ",
   "  x           v   =      =v=   =v    =v=                          x  ",
   "  x                                                               x  ",
   "  x                                                               x  ",
   "  x                                                               x  ",
   "  x                            @                                  x  ",
   "  x                                                               x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                     ",
   "                                                                     "],
   ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEvELS;
